#! /usr/bin/bash

#this script process a text stream with
# the following rules:
# -> if the line contains a letter:
#     -> it's length (in number of fields) is even
#        print the average character lenght
#        of each word within the line.
#    -> it's length (''') is odd
#       print the length of the middle character.
#
# -> if the line is made of numbers (exclusively)
#   print the mean.
# -> EOC print ERROR

echo 'inserta tu texto a probar'
read -r texto_var

echo -e $texto_var | awk '{if (/.*[a-zA-Z].*/)
     {if (!(NF % 2)) {word_length=0; for(i=1; i<= NF; i++) word_length+=length($i); printf("Mean word length: %.2f\n", word_length/NF)}

          else {len=int(NF/2+1); print ("La longitud de la palabra de en medio es "length($len))}
      }
          else if (/^[0-9]+$/) {suma=0; gsub("", " "); for(i=1; i<= NF; i++) suma+=$i; print(suma/NF)}
           else {print("ERROR")}
                }'

