#! /usr/bin/bash

# Sample size (defaults 500)
n_random=${1:-500}
percentiles=${1:-10}

# Drop table
psql -d fdd2db_test -c 'drop table if exists random_test'
# Create table
psql -d fdd2db_test -c 'create table random_test (r_value integer)'
# Populate table

for i in $(seq $n_random)
do
    psql -d fdd2db_test -c "insert into test2 values ($((RANDOM % 101)))"
done
# TODO: extract deciles
((sub_percentiles= $percentiles - 1))
for i in $(seq $sub_percentiles )
do
    psql -d fdd2db_test -c "select $(($i)) as decile, percentile_cont(.$(($i * 10))) within group (order by random) as value from test2"
done
psql -d fdd2db_test -c "select $percentiles as decile, percentile_cont(1) within group (order by random) as value from test2"
#echo "Quantiles"
# echo 1 | awk '{for(i = 1; i <= 10; i++) query=query "percentile_cont(" i/10 ") as percentile_" i ", " }; END {print query}'
# psql -d fdd2db -c 'select percentile_cont(.1) as percentile_1 within group (order by r_value) from random_test'
