#! /bin/bash

# ----------------------------------------
# This script creates and populates
# the following tables. 
# -> universities
# -> programs
# -> students
# ----------------------------------------

# PARAMS
database=${1:-fdd2db}
user=${2:-$(whoami)}

# GLOBAL
N_PROGRAMS=20
N_STUDENTS=10000

echo "Working with database: $database | user: $user"

tables=('universities' 'programs' 'students')

# Drop tables
# Just iterating over an array
# do not worry about this.
for table in ${tables[@]}
do
    echo "Dropping table $table"

    psql -d $database -U $user -c "drop table if exists $table cascade"
done

# ----------------------------------------
# Create tables
# ----------------------------------------
# -> create table universities (reading from csv file)
echo "Creating table universities"
psql -d fdd2db -c "create table if not exists universities (id serial primary key, name varchar(25))"
# -> create table programs
echo "Creating table programs"
psql -d fdd2db -c "create table if not exists programs (id serial primary key, university integer references universities(id), name varchar(25), tuition float)"
# -> create table students 

echo "Creating table students"
psql -d fdd2db -c 'create table if not exists students (id serial primary key, name varchar(50), age integer, program integer references programs(id))'
 
# ----------------------------------------
# Populate tables
# ----------------------------------------
# -> populate universities
echo "Populating table universities"
psql -d fdd2db -c "\copy universities from 'universities.csv' delimiter ','"
# -> populate programs
echo "Populating table programs"
echo $N_PROGRAMS
for i in $(seq $N_PROGRAMS)
do
    echo $i
    # Make sure program is interpreted as string.
    name="'""program_$i""'"
    psql -d fdd2db -c "insert into programs values ($i, $(((RANDOM % 4) + 1)), $name, $((RANDOM * 10)))"
done

for i in $(seq $N_STUDENTS);
do 
	letters=$(for letter in {a..z}; do echo $letter; done | tr '\n' ' '); numbers=$(for number in {18..35}; do echo $number; done | tr '\n' ' ');
	query=$(echo $i | awk -v letters="$letters" -v v_index="$i" -v numbers="$numbers" "BEGIN  {srand(v_index)}; {split(letters,list_letters); 
	split(numbers, list_numbers); for(i = 0; i < 5 + (rand()*100 % 5); i++) r_word = r_word list_letters[int(rand()*length(list_letters)) + 1]; 
	r_age = list_numbers[int(rand()*length(list_numbers)) + 1]; 
	printf( \"insert into students values(%d, '%s', %d, %d)\", v_index, r_word, r_age, r_age % 20 + 1)}");
	psql -d fdd2db -c "$query";
done

