insert into Catalog (url,title) values ('/ebooks/bookshelf/420','6 Best Loved Spanish Literary Classics');
insert into Catalog (url,title) values ('/ebooks/bookshelf/82','Adventure');
insert into Catalog (url,title) values ('/ebooks/bookshelf/5','Africa');
insert into Catalog (url,title) values ('/ebooks/bookshelf/6','African American Writers');
insert into Catalog (url,title) values ('/ebooks/bookshelf/195','Ainslee''s');
insert into Catalog (url,title) values ('/ebooks/bookshelf/196','American Revolutionary War');
insert into Catalog (url,title) values ('/ebooks/bookshelf/7','Anarchism');
insert into Catalog (url,title) values ('/ebooks/bookshelf/150','Animal');
insert into Catalog (url,title) values ('/ebooks/bookshelf/151','Animals-Domestic');
insert into Catalog (url,title) values ('/ebooks/bookshelf/154','Animals-Wild-Birds');
insert into Catalog (url,title) values ('/ebooks/bookshelf/155','Animals-Wild-Insects');
insert into Catalog (url,title) values ('/ebooks/bookshelf/156','Animals-Wild-Mammals');
insert into Catalog (url,title) values ('/ebooks/bookshelf/157','Animals-Wild-Reptiles and Amphibians');
insert into Catalog (url,title) values ('/ebooks/bookshelf/153','Animals-Wild-Trapping');
insert into Catalog (url,title) values ('/ebooks/bookshelf/152','Animals-Wild');
insert into Catalog (url,title) values ('/ebooks/bookshelf/8','Anthropology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/9','Archaeology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/10','Architecture');
insert into Catalog (url,title) values ('/ebooks/bookshelf/112','Argentina');
insert into Catalog (url,title) values ('/ebooks/bookshelf/197','Armour''s Monthly Cook Book');
insert into Catalog (url,title) values ('/ebooks/bookshelf/11','Art');
insert into Catalog (url,title) values ('/ebooks/bookshelf/160','Arthurian Legends');
insert into Catalog (url,title) values ('/ebooks/bookshelf/198','Astounding Stories');
insert into Catalog (url,title) values ('/ebooks/bookshelf/101','Astronomy');
insert into Catalog (url,title) values ('/ebooks/bookshelf/199','Atheism');
insert into Catalog (url,title) values ('/ebooks/bookshelf/113','Australia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/114','Bahá''í Faith');
insert into Catalog (url,title) values ('/ebooks/bookshelf/422','Banned Books List from the American Library Association');
insert into Catalog (url,title) values ('/ebooks/bookshelf/336','Banned Books from Anne Haight''s list');
insert into Catalog (url,title) values ('/ebooks/bookshelf/200','Barnavännen');
insert into Catalog (url,title) values ('/ebooks/bookshelf/159','Bestsellers, American, 1895-1923');
insert into Catalog (url,title) values ('/ebooks/bookshelf/13','Best Books Ever Listings');
insert into Catalog (url,title) values ('/ebooks/bookshelf/15','Bibliomania');
insert into Catalog (url,title) values ('/ebooks/bookshelf/16','Biographies');
insert into Catalog (url,title) values ('/ebooks/bookshelf/201','Biology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/202','Bird-Lore');
insert into Catalog (url,title) values ('/ebooks/bookshelf/203','Birds, Illustrated by Color Photography');
insert into Catalog (url,title) values ('/ebooks/bookshelf/204','Blackwood''s Edinburgh Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/137','Boer War');
insert into Catalog (url,title) values ('/ebooks/bookshelf/115','Botany');
insert into Catalog (url,title) values ('/ebooks/bookshelf/205','British Law');
insert into Catalog (url,title) values ('/ebooks/bookshelf/206','Buchanan''s Journal of Man');
insert into Catalog (url,title) values ('/ebooks/bookshelf/116','Buddhism');
insert into Catalog (url,title) values ('/ebooks/bookshelf/117','Bulgaria');
insert into Catalog (url,title) values ('/ebooks/bookshelf/207','Bulletin de Lille');
insert into Catalog (url,title) values ('/ebooks/bookshelf/181','CIA World Factbooks');
insert into Catalog (url,title) values ('/ebooks/bookshelf/148','Camping');
insert into Catalog (url,title) values ('/ebooks/bookshelf/118','Canada');
insert into Catalog (url,title) values ('/ebooks/bookshelf/208','Canon Law');
insert into Catalog (url,title) values ('/ebooks/bookshelf/209','Celtic Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/210','Chambers''s Edinburgh Journal');
insert into Catalog (url,title) values ('/ebooks/bookshelf/211','Chemistry');
insert into Catalog (url,title) values ('/ebooks/bookshelf/212','Child''s Own Book of Great Musicians');
insert into Catalog (url,title) values ('/ebooks/bookshelf/213','Children''s Anthologies');
insert into Catalog (url,title) values ('/ebooks/bookshelf/214','Children''s Biography');
insert into Catalog (url,title) values ('/ebooks/bookshelf/17','Children''s Book Series');
insert into Catalog (url,title) values ('/ebooks/bookshelf/18','Children''s Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/19','Children''s History');
insert into Catalog (url,title) values ('/ebooks/bookshelf/215','Children''s Instructional Books');
insert into Catalog (url,title) values ('/ebooks/bookshelf/20','Children''s Literature');
insert into Catalog (url,title) values ('/ebooks/bookshelf/216','Children''s Myths, Fairy Tales, etc.');
insert into Catalog (url,title) values ('/ebooks/bookshelf/22','Children''s Picture Books');
insert into Catalog (url,title) values ('/ebooks/bookshelf/217','Children''s Religion');
insert into Catalog (url,title) values ('/ebooks/bookshelf/218','Children''s Verse');
insert into Catalog (url,title) values ('/ebooks/bookshelf/119','Christianity');
insert into Catalog (url,title) values ('/ebooks/bookshelf/23','Christmas');
insert into Catalog (url,title) values ('/ebooks/bookshelf/24','Classical Antiquity');
insert into Catalog (url,title) values ('/ebooks/bookshelf/25','Contemporary Reviews');
insert into Catalog (url,title) values ('/ebooks/bookshelf/219','Continental Monthly');
insert into Catalog (url,title) values ('/ebooks/bookshelf/419','Cookbooks and Cooking');
insert into Catalog (url,title) values ('/ebooks/bookshelf/27','Crafts');
insert into Catalog (url,title) values ('/ebooks/bookshelf/28','Crime Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/29','Crime Nonfiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/220','Current History');
insert into Catalog (url,title) values ('/ebooks/bookshelf/120','Czech');
insert into Catalog (url,title) values ('/ebooks/bookshelf/377','DE Drama');
insert into Catalog (url,title) values ('/ebooks/bookshelf/376','DE Kinderbuch');
insert into Catalog (url,title) values ('/ebooks/bookshelf/375','DE Lyrik');
insert into Catalog (url,title) values ('/ebooks/bookshelf/374','DE Prosa');
insert into Catalog (url,title) values ('/ebooks/bookshelf/378','DE Sachbuch');
insert into Catalog (url,title) values ('/ebooks/bookshelf/30','Detective Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/222','Dew Drops');
insert into Catalog (url,title) values ('/ebooks/bookshelf/221','De Aarde en haar Volken');
insert into Catalog (url,title) values ('/ebooks/bookshelf/223','Donahoe''s Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/31','Early English Text Society');
insert into Catalog (url,title) values ('/ebooks/bookshelf/224','Ecology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/138','Education');
insert into Catalog (url,title) values ('/ebooks/bookshelf/121','Egypt');
insert into Catalog (url,title) values ('/ebooks/bookshelf/32','Engineering');
insert into Catalog (url,title) values ('/ebooks/bookshelf/139','English Civil War');
insert into Catalog (url,title) values ('/ebooks/bookshelf/33','Erotic Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/34','Esperanto');
insert into Catalog (url,title) values ('/ebooks/bookshelf/406','FR Beaux-Arts');
insert into Catalog (url,title) values ('/ebooks/bookshelf/382','FR Biographie, Mémoires, Journal intime, Correspondance');
insert into Catalog (url,title) values ('/ebooks/bookshelf/306','FR Chansons');
insert into Catalog (url,title) values ('/ebooks/bookshelf/408','FR Chroniques');
insert into Catalog (url,title) values ('/ebooks/bookshelf/392','FR Contes');
insert into Catalog (url,title) values ('/ebooks/bookshelf/387','FR Droit et Justice');
insert into Catalog (url,title) values ('/ebooks/bookshelf/380','FR Education et Enseignement');
insert into Catalog (url,title) values ('/ebooks/bookshelf/307','FR Femmes');
insert into Catalog (url,title) values ('/ebooks/bookshelf/390','FR Guerres');
insert into Catalog (url,title) values ('/ebooks/bookshelf/309','FR Histoire');
insert into Catalog (url,title) values ('/ebooks/bookshelf/385','FR Humour');
insert into Catalog (url,title) values ('/ebooks/bookshelf/310','FR Illustrateurs');
insert into Catalog (url,title) values ('/ebooks/bookshelf/311','FR Jeunesse');
insert into Catalog (url,title) values ('/ebooks/bookshelf/384','FR Langues');
insert into Catalog (url,title) values ('/ebooks/bookshelf/407','FR La Première Guerre Mondiale, 1914-1918');
insert into Catalog (url,title) values ('/ebooks/bookshelf/313','FR Littérature');
insert into Catalog (url,title) values ('/ebooks/bookshelf/337','FR Littérature francophone');
insert into Catalog (url,title) values ('/ebooks/bookshelf/416','FR Livres, Collections et Bibliophilie');
insert into Catalog (url,title) values ('/ebooks/bookshelf/315','FR Musique');
insert into Catalog (url,title) values ('/ebooks/bookshelf/417','FR Métiers et Artisanat');
insert into Catalog (url,title) values ('/ebooks/bookshelf/395','FR Nouveautés');
insert into Catalog (url,title) values ('/ebooks/bookshelf/317','FR Nouvelles');
insert into Catalog (url,title) values ('/ebooks/bookshelf/383','FR Occultisme');
insert into Catalog (url,title) values ('/ebooks/bookshelf/318','FR Peinture');
insert into Catalog (url,title) values ('/ebooks/bookshelf/386','FR Peuples et Sociétés');
insert into Catalog (url,title) values ('/ebooks/bookshelf/381','FR Philosophie, Religion et Morale');
insert into Catalog (url,title) values ('/ebooks/bookshelf/388','FR Politique');
insert into Catalog (url,title) values ('/ebooks/bookshelf/35','FR Poésie');
insert into Catalog (url,title) values ('/ebooks/bookshelf/319','FR Presse');
insert into Catalog (url,title) values ('/ebooks/bookshelf/320','FR Prix Nobel');
insert into Catalog (url,title) values ('/ebooks/bookshelf/322','FR Sciences et Techniques');
insert into Catalog (url,title) values ('/ebooks/bookshelf/321','FR Science fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/391','FR Services publics');
insert into Catalog (url,title) values ('/ebooks/bookshelf/393','FR Sports et loisirs');
insert into Catalog (url,title) values ('/ebooks/bookshelf/396','FR Séduction et libertinage');
insert into Catalog (url,title) values ('/ebooks/bookshelf/323','FR Théâtre');
insert into Catalog (url,title) values ('/ebooks/bookshelf/394','FR Villes');
insert into Catalog (url,title) values ('/ebooks/bookshelf/397','FR Voyages et pays');
insert into Catalog (url,title) values ('/ebooks/bookshelf/400','Famous Scots Series');
insert into Catalog (url,title) values ('/ebooks/bookshelf/36','Fantasy');
insert into Catalog (url,title) values ('/ebooks/bookshelf/37','Folklore');
insert into Catalog (url,title) values ('/ebooks/bookshelf/145','Forestry');
insert into Catalog (url,title) values ('/ebooks/bookshelf/122','France');
insert into Catalog (url,title) values ('/ebooks/bookshelf/226','Garden and Forest');
insert into Catalog (url,title) values ('/ebooks/bookshelf/411','General Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/227','Geology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/123','Germany');
insert into Catalog (url,title) values ('/ebooks/bookshelf/38','German Language Books');
insert into Catalog (url,title) values ('/ebooks/bookshelf/228','Godey''s Lady''s Book');
insert into Catalog (url,title) values ('/ebooks/bookshelf/229','Golden Days for Boys and Girls');
insert into Catalog (url,title) values ('/ebooks/bookshelf/39','Gothic Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/230','Graham''s Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/124','Greece');
insert into Catalog (url,title) values ('/ebooks/bookshelf/231','Harper''s New Monthly Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/232','Harper''s Young People');
insert into Catalog (url,title) values ('/ebooks/bookshelf/40','Harvard Classics');
insert into Catalog (url,title) values ('/ebooks/bookshelf/125','Hinduism');
insert into Catalog (url,title) values ('/ebooks/bookshelf/41','Historical Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/42','Horror');
insert into Catalog (url,title) values ('/ebooks/bookshelf/43','Horticulture');
insert into Catalog (url,title) values ('/ebooks/bookshelf/44','Humor');
insert into Catalog (url,title) values ('/ebooks/bookshelf/418','IT Agraria');
insert into Catalog (url,title) values ('/ebooks/bookshelf/410','IT Archeologia e Storia dell''arte');
insert into Catalog (url,title) values ('/ebooks/bookshelf/409','IT Architettura');
insert into Catalog (url,title) values ('/ebooks/bookshelf/342','IT Arte varia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/343','IT Biografie');
insert into Catalog (url,title) values ('/ebooks/bookshelf/344','IT Botanica');
insert into Catalog (url,title) values ('/ebooks/bookshelf/345','IT Cucina');
insert into Catalog (url,title) values ('/ebooks/bookshelf/346','IT Discorsi e Orazioni');
insert into Catalog (url,title) values ('/ebooks/bookshelf/347','IT Economia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/348','IT Filosofia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/349','IT Folklore');
insert into Catalog (url,title) values ('/ebooks/bookshelf/350','IT Geografia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/351','IT Legge');
insert into Catalog (url,title) values ('/ebooks/bookshelf/352','IT Letteratura');
insert into Catalog (url,title) values ('/ebooks/bookshelf/353','IT Letteratura per ragazzi');
insert into Catalog (url,title) values ('/ebooks/bookshelf/354','IT Linguistica');
insert into Catalog (url,title) values ('/ebooks/bookshelf/399','IT Miscellanea');
insert into Catalog (url,title) values ('/ebooks/bookshelf/355','IT Musica');
insert into Catalog (url,title) values ('/ebooks/bookshelf/356','IT Narrativa varia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/357','IT Numismatica');
insert into Catalog (url,title) values ('/ebooks/bookshelf/358','IT Poesia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/359','IT Psicologia e Sociologia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/360','IT Racconti');
insert into Catalog (url,title) values ('/ebooks/bookshelf/361','IT Religione e Spiritualità');
insert into Catalog (url,title) values ('/ebooks/bookshelf/362','IT Romanzi');
insert into Catalog (url,title) values ('/ebooks/bookshelf/363','IT Romanzi storici');
insert into Catalog (url,title) values ('/ebooks/bookshelf/364','IT Salute');
insert into Catalog (url,title) values ('/ebooks/bookshelf/365','IT Scienza');
insert into Catalog (url,title) values ('/ebooks/bookshelf/398','IT Scienze militari');
insert into Catalog (url,title) values ('/ebooks/bookshelf/366','IT Scienze politiche');
insert into Catalog (url,title) values ('/ebooks/bookshelf/367','IT Storia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/368','IT Teatro dialettale');
insert into Catalog (url,title) values ('/ebooks/bookshelf/369','IT Teatro in prosa');
insert into Catalog (url,title) values ('/ebooks/bookshelf/370','IT Teatro in versi');
insert into Catalog (url,title) values ('/ebooks/bookshelf/371','IT Tecnologia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/372','IT Umorismo');
insert into Catalog (url,title) values ('/ebooks/bookshelf/373','IT Viaggi');
insert into Catalog (url,title) values ('/ebooks/bookshelf/327','Illustrators');
insert into Catalog (url,title) values ('/ebooks/bookshelf/45','India');
insert into Catalog (url,title) values ('/ebooks/bookshelf/126','Islam');
insert into Catalog (url,title) values ('/ebooks/bookshelf/127','Italy');
insert into Catalog (url,title) values ('/ebooks/bookshelf/128','Judaism');
insert into Catalog (url,title) values ('/ebooks/bookshelf/234','Journal of Entomology and Zoology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/235','L''Illustration');
insert into Catalog (url,title) values ('/ebooks/bookshelf/46','Language Education');
insert into Catalog (url,title) values ('/ebooks/bookshelf/404','Latter Day Saints');
insert into Catalog (url,title) values ('/ebooks/bookshelf/236','Lippincott''s Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/237','Little Folks');
insert into Catalog (url,title) values ('/ebooks/bookshelf/414','London Medical Gazette');
insert into Catalog (url,title) values ('/ebooks/bookshelf/47','Love');
insert into Catalog (url,title) values ('/ebooks/bookshelf/146','Manufacturing');
insert into Catalog (url,title) values ('/ebooks/bookshelf/415','Maps and Cartography');
insert into Catalog (url,title) values ('/ebooks/bookshelf/402','Masterpieces in Colour');
insert into Catalog (url,title) values ('/ebooks/bookshelf/102','Mathematics');
insert into Catalog (url,title) values ('/ebooks/bookshelf/239','McClure''s Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/48','Medicine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/401','Mediæval Town Series');
insert into Catalog (url,title) values ('/ebooks/bookshelf/105','Microbiology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/109','Microscopy');
insert into Catalog (url,title) values ('/ebooks/bookshelf/240','Mother Earth');
insert into Catalog (url,title) values ('/ebooks/bookshelf/49','Movie Books');
insert into Catalog (url,title) values ('/ebooks/bookshelf/241','Mrs Whittelsey''s Magazine for Mothers and Daughters');
insert into Catalog (url,title) values ('/ebooks/bookshelf/50','Music');
insert into Catalog (url,title) values ('/ebooks/bookshelf/129','Mycology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/51','Mystery Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/52','Mythology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/149','Napoleonic(Bookshelf)');
insert into Catalog (url,title) values ('/ebooks/bookshelf/53','Native America');
insert into Catalog (url,title) values ('/ebooks/bookshelf/54','Natural History');
insert into Catalog (url,title) values ('/ebooks/bookshelf/130','New Zealand');
insert into Catalog (url,title) values ('/ebooks/bookshelf/244','Northern Nut Growers Association');
insert into Catalog (url,title) values ('/ebooks/bookshelf/131','Norway');
insert into Catalog (url,title) values ('/ebooks/bookshelf/245','Notes and Queries');
insert into Catalog (url,title) values ('/ebooks/bookshelf/246','Noteworthy Trials(Bookshelf)');
insert into Catalog (url,title) values ('/ebooks/bookshelf/55','One Act Plays');
insert into Catalog (url,title) values ('/ebooks/bookshelf/56','Opera');
insert into Catalog (url,title) values ('/ebooks/bookshelf/247','Our Young Folks');
insert into Catalog (url,title) values ('/ebooks/bookshelf/88','PT Arte');
insert into Catalog (url,title) values ('/ebooks/bookshelf/89','PT Biografia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/90','PT Ciência e Técnica');
insert into Catalog (url,title) values ('/ebooks/bookshelf/91','PT Contos');
insert into Catalog (url,title) values ('/ebooks/bookshelf/92','PT História');
insert into Catalog (url,title) values ('/ebooks/bookshelf/93','PT Infantil e Juvenil');
insert into Catalog (url,title) values ('/ebooks/bookshelf/94','PT Língua Portuguesa');
insert into Catalog (url,title) values ('/ebooks/bookshelf/95','PT Navegações e Explorações');
insert into Catalog (url,title) values ('/ebooks/bookshelf/96','PT Periódicos');
insert into Catalog (url,title) values ('/ebooks/bookshelf/97','PT Poesia');
insert into Catalog (url,title) values ('/ebooks/bookshelf/98','PT Política e Sociedade');
insert into Catalog (url,title) values ('/ebooks/bookshelf/99','PT Romance');
insert into Catalog (url,title) values ('/ebooks/bookshelf/100','PT Teatro');
insert into Catalog (url,title) values ('/ebooks/bookshelf/132','Paganism');
insert into Catalog (url,title) values ('/ebooks/bookshelf/57','Philosophy');
insert into Catalog (url,title) values ('/ebooks/bookshelf/158','Photography');
insert into Catalog (url,title) values ('/ebooks/bookshelf/103','Physics');
insert into Catalog (url,title) values ('/ebooks/bookshelf/110','Physiology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/58','Pirates, Buccaneers, Corsairs, etc.');
insert into Catalog (url,title) values ('/ebooks/bookshelf/59','Plays');
insert into Catalog (url,title) values ('/ebooks/bookshelf/248','Poetry, A Magazine of Verse');
insert into Catalog (url,title) values ('/ebooks/bookshelf/60','Poetry');
insert into Catalog (url,title) values ('/ebooks/bookshelf/61','Politics');
insert into Catalog (url,title) values ('/ebooks/bookshelf/249','Popular Science Monthly');
insert into Catalog (url,title) values ('/ebooks/bookshelf/250','Prairie Farmer');
insert into Catalog (url,title) values ('/ebooks/bookshelf/62','Precursors of Science Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/63','Project Gutenberg');
insert into Catalog (url,title) values ('/ebooks/bookshelf/64','Psychology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/252','Punch');
insert into Catalog (url,title) values ('/ebooks/bookshelf/253','Punchinello');
insert into Catalog (url,title) values ('/ebooks/bookshelf/65','Racism');
insert into Catalog (url,title) values ('/ebooks/bookshelf/66','Reference');
insert into Catalog (url,title) values ('/ebooks/bookshelf/412','Romantic Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/67','School Stories');
insert into Catalog (url,title) values ('/ebooks/bookshelf/106','Science');
insert into Catalog (url,title) values ('/ebooks/bookshelf/68','Science Fiction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/403','Science Fiction by Women');
insert into Catalog (url,title) values ('/ebooks/bookshelf/256','Scientific American');
insert into Catalog (url,title) values ('/ebooks/bookshelf/144','Scouts');
insert into Catalog (url,title) values ('/ebooks/bookshelf/257','Scribner''s Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/69','Short Stories');
insert into Catalog (url,title) values ('/ebooks/bookshelf/70','Slavery');
insert into Catalog (url,title) values ('/ebooks/bookshelf/134','Sociology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/135','South Africa');
insert into Catalog (url,title) values ('/ebooks/bookshelf/71','South America');
insert into Catalog (url,title) values ('/ebooks/bookshelf/140','Spanish American War');
insert into Catalog (url,title) values ('/ebooks/bookshelf/258','St. Nicholas Magazine for Boys and Girls');
insert into Catalog (url,title) values ('/ebooks/bookshelf/72','Suffrage');
insert into Catalog (url,title) values ('/ebooks/bookshelf/143','Technology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/259','The Aldine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/260','The American Architect and Building News');
insert into Catalog (url,title) values ('/ebooks/bookshelf/423','The American Bee Journal');
insert into Catalog (url,title) values ('/ebooks/bookshelf/261','The American Journal of Archaeology');
insert into Catalog (url,title) values ('/ebooks/bookshelf/262','The American Missionary');
insert into Catalog (url,title) values ('/ebooks/bookshelf/263','The American Quarterly Review');
insert into Catalog (url,title) values ('/ebooks/bookshelf/264','The Arena');
insert into Catalog (url,title) values ('/ebooks/bookshelf/265','The Argosy');
insert into Catalog (url,title) values ('/ebooks/bookshelf/266','The Atlantic Monthly');
insert into Catalog (url,title) values ('/ebooks/bookshelf/267','The Baptist Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/268','The Bay State Monthly');
insert into Catalog (url,title) values ('/ebooks/bookshelf/269','The Botanical Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/270','The Brochure Series of Architectural Illustration');
insert into Catalog (url,title) values ('/ebooks/bookshelf/271','The Catholic World');
insert into Catalog (url,title) values ('/ebooks/bookshelf/272','The Christian Foundation');
insert into Catalog (url,title) values ('/ebooks/bookshelf/273','The Church of England Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/274','The Contemporary Review');
insert into Catalog (url,title) values ('/ebooks/bookshelf/275','The Economist');
insert into Catalog (url,title) values ('/ebooks/bookshelf/276','The Esperantist');
insert into Catalog (url,title) values ('/ebooks/bookshelf/277','The Galaxy');
insert into Catalog (url,title) values ('/ebooks/bookshelf/278','The Girls Own Paper');
insert into Catalog (url,title) values ('/ebooks/bookshelf/279','The Great Round World And What Is Going On In It');
insert into Catalog (url,title) values ('/ebooks/bookshelf/413','The Haslemere Museum Gazette');
insert into Catalog (url,title) values ('/ebooks/bookshelf/280','The Idler');
insert into Catalog (url,title) values ('/ebooks/bookshelf/281','The Illustrated War News');
insert into Catalog (url,title) values ('/ebooks/bookshelf/282','The International Magazine of Literature, Art, and Science');
insert into Catalog (url,title) values ('/ebooks/bookshelf/283','The Irish Ecclesiastical Record');
insert into Catalog (url,title) values ('/ebooks/bookshelf/284','The Irish Penny Journal');
insert into Catalog (url,title) values ('/ebooks/bookshelf/285','The Journal of Negro History');
insert into Catalog (url,title) values ('/ebooks/bookshelf/286','The Knickerbocker');
insert into Catalog (url,title) values ('/ebooks/bookshelf/287','The Mayflower');
insert into Catalog (url,title) values ('/ebooks/bookshelf/288','The Menorah Journal');
insert into Catalog (url,title) values ('/ebooks/bookshelf/289','The Mentor');
insert into Catalog (url,title) values ('/ebooks/bookshelf/290','The Mirror of Literature, Amusement, and Instruction');
insert into Catalog (url,title) values ('/ebooks/bookshelf/291','The Mirror of Taste, and Dramatic Censor');
insert into Catalog (url,title) values ('/ebooks/bookshelf/292','The National Preacher');
insert into Catalog (url,title) values ('/ebooks/bookshelf/293','The North American Medical and Surgical Journal');
insert into Catalog (url,title) values ('/ebooks/bookshelf/294','The Nursery');
insert into Catalog (url,title) values ('/ebooks/bookshelf/73','The Philatelic Digital Library Project');
insert into Catalog (url,title) values ('/ebooks/bookshelf/295','The Scrap Book');
insert into Catalog (url,title) values ('/ebooks/bookshelf/296','The Speaker');
insert into Catalog (url,title) values ('/ebooks/bookshelf/297','The Stars and Stripes');
insert into Catalog (url,title) values ('/ebooks/bookshelf/298','The Strand Magazine');
insert into Catalog (url,title) values ('/ebooks/bookshelf/299','The Unpopular Review');
insert into Catalog (url,title) values ('/ebooks/bookshelf/300','The Writer');
insert into Catalog (url,title) values ('/ebooks/bookshelf/301','The Yellow Book');
insert into Catalog (url,title) values ('/ebooks/bookshelf/74','Transportation');
insert into Catalog (url,title) values ('/ebooks/bookshelf/75','Travel');
insert into Catalog (url,title) values ('/ebooks/bookshelf/141','US Civil War');
insert into Catalog (url,title) values ('/ebooks/bookshelf/76','United Kingdom');
insert into Catalog (url,title) values ('/ebooks/bookshelf/136','United States');
insert into Catalog (url,title) values ('/ebooks/bookshelf/302','United States Law');
insert into Catalog (url,title) values ('/ebooks/bookshelf/77','Western');
insert into Catalog (url,title) values ('/ebooks/bookshelf/78','Witchcraft');
insert into Catalog (url,title) values ('/ebooks/bookshelf/80','Women''s Travel Journals');
insert into Catalog (url,title) values ('/ebooks/bookshelf/147','Woodwork');
insert into Catalog (url,title) values ('/ebooks/bookshelf/142','World War I');
insert into Catalog (url,title) values ('/ebooks/bookshelf/325','World War II');
insert into Catalog (url,title) values ('/ebooks/bookshelf/303','Zoology');
