#! /bin/bash

echo 'inserta tu texto a probar'

read -r texto_var

echo -e  $texto_var | awk '{if (/.*[a-zA-Z].*/)

 {if (!(NF % 2))
        {word_length=0; for(i=1; i <= NF; i++) word_length+=length($i); printf("Promedio de longitud: %.2f\n", word_length/NF)}

 else {
        print "Longitud palabra central: ", length($(NF/2+1))
       }
  }

                            else
                                 if (/^[0-9 ]+$/) {gsub(""," ");suma=0; for(i=1; i <= NF; i++) suma+=int($i); printf("Promedio: %.2f\n", suma/NF)}
                                         else {print "error"}


                              }'
