#! /bin/bash

# ----------------------------------------
# This script creates and populates
# the following tables.
# -> universities
# -> programs
# -> students
# ----------------------------------------

# PARAMS
database=${1:-fdd2db}
user=${2:-$(whoami)}

# GLOBAL
N_PROGRAMS=20
N_STUDENTS=100000

echo "Working with database: $database | user: $user"

tables=('universities' 'programs' 'students')

# Drop tables
# Just iterating over an array
# do not worry about this.
for table in ${tables[@]}
do
    echo "Dropping table $table"

    psql -d $database -U $user -c "drop table if exists $table cascade"
done

# ----------------------------------------
# Create tables
# ----------------------------------------
# -> create table universities (reading from csv file)
echo "Creating table universities"
psql -d fdd2db -c "create table if not exists universities (id serial primary key, name varchar(25))"
# -> create table programs
echo "Creating table programs"
psql -d fdd2db -c "create table if not exists programs (id serial primary key, university integer references universities(id), name varchar(25), tuition float)"
# -> create table students
# TODO
# -> create table students with the structure
#    (id, name, age, program)
#    make sure to use the correct
#    datatypes.
